#!/usr/bin/env bash
set -eu
if [ $# -gt 0 ]; then
  docker=true
else
  docker=false
fi
if "$docker"; then
  export DEBIAN_FRONTEND=noninteractive
  sed -Ei 's/^# deb-src/deb-src/' /etc/apt/sources.list
  sudo=
  y=-y
else
  sudo=sudo
  y=
fi
$sudo apt update
$sudo apt install $y \
  asciidoctor \
  gcc-aarch64-linux-gnu \
  gcc-arm-linux-gnueabihf \
  gdb-multiarch \
  screen \
;
$sudo apt build-dep binutils qemu $y
