= ARM Assembly Cheat
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

ARM assembly userland minimal examples. Runnable asserts on x86 host with QEMU. Tested on Ubuntu 18.04 host.

toc::[]

== Getting started

Ubuntu 16.04 amd64:

....
./configure
....

Build all examples:

....
make
....

Run a single example on an emulator:

....
make run-<basename-no-extension>
....

E.g.:

....
make run-hello_driver
....

will run:

....
hello_driver.S
....

Test that all examples exit with status 0:

....
make test
....

Debug one example with GDB:

....
make debug-hello_driver
....

== About

Top level examples target the armv7 ISA (32-bit). New AArch64 features will be put in subdirectory.

`qemu-arm-static` is used for emulation. It translates ARM to x86, and forwards system calls to the kernel.

OS portability is achieved with the C standard library which makes system calls for us.

Non OS portable examples will be clearly labeled with their OS.

== Infrastructure

These examples show how our tooling works:

. link:fail.S[]
. link:hello_c.c[]
. link:hello_driver.S[]

== Instructions

Grouping loosely based on that of the manual.

=== Load/store instructions

. link:mov.S[]
. link:push.S[]

https://stackoverflow.com/questions/14046686/why-use-ldr-over-mov-or-vice-versa-in-arm-assembly

=== Branch instructions

. link:beq.S[]
. link:b.S[]
. link:bl.S[]

=== Data processing instructions

. link:add.S[]
. link:and.S[]
. link:mul.S[]
. link:sub.S[]

== Instruction encoding

Every ARMv7 instruction is 4 bytes long.

<<Thumb>> is an alternative encoding.

=== Thumb

Variable bit encoding where instructions are either 4 or 2 bytes.

In general cannot encode conditional instructions, but <<thumb-2>> can.

Example:

....
make run-thumb
....

Outcome: it does not blow up.

Source:

* link:driver_thumb.c[]
* link:thumb.S[]

https://stackoverflow.com/questions/28669905/what-is-the-difference-between-the-arm-thumb-and-thumb-2-instruction-encodings

=== Thumb-2

Newer version of thumb that allows encoding almost all instructions, TODO example.

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0471i/CHDFEDDB.html

== Calling convention

http://stackoverflow.com/questions/8422287/calling-c-functions-from-arm-assembly

Call the C `puts("hello world")` and `exit(0)` functions from assembly:

....
make run-c_from_arm
....

Source: link:c_from_arm.S[]

Don't forget that stack must be 8 byte aligned.

== Linux system calls

Do a `write` and `exit` raw Linux system calls:

....
make -C linux
....

Outcome:

....
hello world
....

Source: link:linux/hello.S[].

Unlike most our other examples, which use the C standard library for portability, this one can only be run on Linux.

== Theory

. link:how-to-play-with-arm.md[How to play with ARM]
. link:introduction.md[Introduction]
. link:versions.md[Versions]
.. link:aarch64.md[AArch64]
. link:calling-conventions.md[Calling conventions]
. link:extensions.md[Extensions]
.. link:thumb.md[Thumb]
. link:vs-x86.md[Vs x86]
. link:compilers.md[Compilers]
. link:free-implementations.md[Free implementations]
. link:gas.md[GAS]
. link:registers.md[Registers]
. link:flags.md[Flags]
. link:system-programming.md[System programming]
. link:isa-documentation.md[ISA documentation]
. link:glossary.md[Glossary]
. link:bibliography.md[Bibliography]
