= ARM Assembly Cheat
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

ARMv7 and ARMv8 assembly userland minimal examples tutorial. Runnable asserts on x86 host with QEMU user mode. Nice GDB step debug setup. Tested on Ubuntu 18.04 host.

toc::[]

== Getting started

Clone, configure, build and run all ARMv7 and ARMv8 examples through QEMU user, and assert that they exit with status 0:

....
git clone --recursive https://github.com/cirosantilli/arm-assembly-cheat
cd arm-assembly-cheat
./configure
make test
....

The armv7 examples are all located under the link:v7[] directory. Run all of them:

....
cd v7
make test
....

Run just one of them:

....
cd v7
make test-<basename-no-extension>
....

E.g.:

....
make test-add
....

will run link:v7/add.S[].

<<armv8>> examples are all located under the link:v8[] directory. They can be run in the same way as ARMv7 examples:

....
cd v8
make test-mov
....

Alternatively, to help with tab complete, the following all do the same thing:

....
./t hello_driver
./t hello_driver.
./t hello_driver.out
....

Almost all example don't output anything, they just assert that the computations are as expected and exit 0 is that was the case.

Try messing with the examples to see them fail, e.g. link:fail.S[]. You should see something like:

....
error 1 at line 7
TEST FAILED: fail.out
Makefile:78: recipe for target 'test' failed
make: *** [test] Error 1
....

So look how nice we are: we even gave you the line number of the failing assert!

Just build the examples without running:

....
make
....

Clean the examples:

....
make clean
....

This does not clean QEMU builds themselves. To do that run:

....
make qemu-clean
....

=== GDB step debug

Debug one example with GDB:

....
make gdb-add
....

Shortcut:

....
./t -g add
....

This leaves us right at the end of `asm_main`, and at the start of the assembly code in the `.S` file.

Stop on a different symbol instead:

....
make GDB_BREAK=main gdb-add
....

Shortcut:

....
./t -b main -g add
....

It is not possible to restart the running program from GDB as in `gdbserver --multi` unfortunately: https://stackoverflow.com/questions/51357124/how-to-restart-qemu-user-mode-programs-from-the-gdb-stub-as-in-gdbserver-multi

Quick GDB tips:

* print a register:
+
....
i r r0
....
+
Bibliography: https://stackoverflow.com/questions/5429137/how-to-print-register-values-in-gdb
* print an array of 4 32-bit integers in hex:
+
....
p/x (unsigned[4])my_array_0
....
+
Bibliography: https://stackoverflow.com/questions/32300718/printing-array-from-bss-in-gdb
* print the address of a variable:
+
....
p &my_array_0
....

Bibliography: https://stackoverflow.com/questions/20590155/how-to-single-step-arm-assembler-in-gdb-on-qemu/51310791#51310791

=== Disassemble

Even though <<gdb-step-debug>> can already disassemble instructions for us, it is sometimes useful to have the disassembly in a text file for further examination.

Disassemble all examples:

....
make -j `nproc` objdump
....

Disassemble one example:

....
make add.objdump
....

Examine one disassembly:

....
less -p asm_main add.objdump
....

This jumps directly to `asm_main`, which is what you likely want to see.

Disassembly is still useful even though we are writing assembly because the assembler can do some non-obvious magic that we want to understand.

==== .n and .w suffixes

When reading the disassembly, many instructions have either a `.n` or `.w` suffix.

`.n` means narrow, and stands for the Thumb encoding of an instructions, while `.w` means wide and stands for the ARM encoding.

Bibliography: https://stackoverflow.com/questions/27147043/n-suffix-to-branch-instruction

=== Run on Raspberry Pi 2

Yay! Let's see if this actually works on real hardware, or if it is just an emulation pipe dream?

We will just compile natively, since I'm not in the mood for cross compilation hell today.

link:https://en.wikipedia.org/wiki/Raspberry_Pi[According to Wikipedia] the Raspberry Pi 2 V 1.1 which I have has a BCM2836, which has an link:https://en.wikipedia.org/wiki/ARM_Cortex-A7[ARM Cortex-A7], which implements ARMv7-A, <<vfp,VFPv4>> and <<neon>>.

Therefore we will only be able to run `v7` examples on that board.

First connect to your Pi through SSH as explained at: https://stackoverflow.com/questions/16040128/hook-up-raspberry-pi-via-ethernet-to-laptop-without-router/39086537#39086537

Inside the Pi:

....
sudo apt-get update
sudo apt-get install git
git clone https://github.com/cirosantilli/arm-assembly-cheat
cd arm-assembly-cheat
cd v7
make NATIVE=y test
make NATIVE=y gdb-add
....

=== Build your own toolchain

If you are like me, and you don't trust distro blobs, or if your distro does not provide working blobs, here goes a working procedure to use your own pristine cross toolchain. 

Build the toolchain with crosstool-ng as explained at: https://stackoverflow.com/revisions/51310756/6

Then run with:

....
make \
  CTNG=crosstool-ng/.build/ct_prefix \
  PREFIX=arm-cortex_a15-linux-gnueabihf \
  test \
;
....

Ideally we should just add crosstool-ng as a submodule here and automate from there, but I've done that like 5 times this month and I'm lazy now.

=== Build documentation

If you don't like reading on GitHub, the HTML documentation can be generated from the README with:

....
make doc
xdg-open README.html
....

== About

`qemu-arm-static` is used for emulation on x86 hosts. It translates ARM to x86, and forwards system calls to the host kernel.

OS portability is achieved with the C standard library which makes system calls for us.

Non OS portable examples will be clearly labeled with their OS, e.g.: <<linux-system-calls>>.

These examples show how our insfrastructure works:

* link:fail.S[]
* link:v7/hello_driver.S[]
* link:hello_common.S[]

=== C driver

We link all examples agains a C program: link:main.c[]. Sample simplified commands:

....
arm-linux-gnueabihf-gcc -c -o 'main.o' 'main.c'
arm-linux-gnueabihf-gcc -c -o 'sub.o' 'sub.S'
arm-linux-gnueabihf-gcc -o 'sub.out' 'sub.o' main.o
....

The C driver then just calls `asm_main`, which each `.S` example implements.

This allows us to easily use the C standard libray portably: from the point of view of GCC, everything looks like a regular C program, which does the required glibc initialization before `main()`.

== Registers

Examples: link:v7/regs.S[]

Bibliography: <<armarm7>> A2.3 "ARM core registers".

== Instructions

Grouping loosely based on that of the <<armarm7>> Chapter A4 "The Instruction Sets".

=== Branch instructions

==== b

Unconditional branch.

Example: link:v7/b.S[]

The encoding stores `pc` offsets in 24 bits. The destination must be a multiple of 4, which is easy since all instructions are 4 bytes.

This allows for 26 bit long jumps, which is 64 MiB.

TODO: what to do if we want to jump longer than that?

==== beq

Branch if equal based on the status registers.

Example: link:v7/beq.S[].

The family of instructions includes:

* `beq`: branch if equal
* `bne`: branch if not equal
* `ble`: less or equal
* `bge`: greater or equal
* `blt`: less than
* `bgt`: greater than

==== bl

Branch with link, i.e. branch and store the return address on the `rl` register.

Example: link:v7/bl.S[]

This is the major way to make function calls.

The current ARM / Thumb mode is encoded in the least significant bit of lr.

===== bx

`bx`: branch and switch between ARM / Thumb mode, encoded in the least significant bit of the given register.

`bx lr` is the main way to return from function calls after a `bl` call.

Since `bl` encodes the current ARM / Thumb in the register, `bx` keeps the mode unchanged by default.

==== cbz

Compare and branch if zero.

Example: link:v8/cbz.S[]

Only in ARMv8 and ARMv7 Thumb mode, not in armv7 ARM mode.

==== Conditional execution

Weirdly, <<b>> and family are not the only instructions that can execute conditionally on the flags: the same also applies to most instructions, e.g. `add`.

Example: link:v7/cond.S[]

Just add the usual `eq`, `ne`, etc. suffixes just as for `b`.

=== Load and store instructions

In ARM, there are only two instruction families that do memory access: <<ldr>>  to load and <<str>> to store.

Everything else works on register and immediates.

This is part of the RISC-y beauty of the ARM instruction set, unlike x86 in which several operations can read from memory, and helps to predict how to optimize for a given CPU pipeline.

This kind of architecture is called a link:https://en.wikipedia.org/wiki/Load/store_architecture[Load/store architecture].

==== ldr

===== ldr magic

The `ldr` assembly directive can automatically create hidden variables and load them from memory with PC relative loads.

Example: link:v7/ldr_magic.S[]

This is done basically because all instructions are 32-bit wide, and there is not enough space to encode 32-bit addresses in them.

Bibliography:

* https://stackoverflow.com/questions/37840754/what-does-an-equals-sign-on-the-right-side-of-a-ldr-instruction-in-arm-mean
* https://stackoverflow.com/questions/17214962/what-is-the-difference-between-label-equals-sign-and-label-brackets-in-ar
* https://stackoverflow.com/questions/14046686/why-use-ldr-over-mov-or-vice-versa-in-arm-assembly

===== Addressing modes

Example: link:v7/address_modes.S[]

Load and store instructions can update the source register with the following modes:

* offset: add an offset, don't change the address register. Notation:
+
....
ldr r1, [r0, #4]
....
* pre-indexed: change the address register, and then use it modified. Notation:
+
....
ldr r1, [r0, #4]!
....
* post-indexed: use the address register unmodified, and then modify it. Notation:
+
....
ldr r1, [r0] #4
....

The offset itself can come from the following sources:

* immediate
* register
* scaled register: left shift the register and use that as an offset

The indexed modes are convenient to loop over arrays.

Bibliography: <<armarm7>>:

* A4.6.5 "Addressing modes"
* A8.5 "Memory accesses"

====== Loop over array

As an application of the post-indexed addressing mode, let's increment an array.

Example: link:v7/inc_array.S[]

===== ldr width

There are `ldr` variants that load less than full 4 bytes:

* link:v7/ldrb.S[]
* link:v7/ldrh.S[]

==== str

Store from memory into registers.

Example: link:v7/str.S[]

Basically everything that applies to <<ldr>> also applies here so we won't go into much detail.

==== ldmia

Pop values form stack into the register and optionally update the address register.

`stmdb` is the push version.

Example: link:v7/ldmia.S[]

The mnemonics stand for:

* `stmdb`: STore Multiple Decrement Before
* `ldmia`: LoaD Multiple Increment After

Example: link:v7/push.S[]

`push` and `pop` are just mnemonics `stdmdb` and `ldmia` using the stack pointer `sp` as address register:

....
stmdb sp!, reglist
ldmia sp!, reglist
....

The `!` indicates that we want to update the register.

The registers are encoded as single bits inside the instruction: each bit represents one register.

As a consequence, the push order is fixed no matter how you write the assembly instruction: there is just not enough space to encode ordering.

AArch64 loses those instructions, likely because it was not possible anymore to encode all registers: http://stackoverflow.com/questions/27941220/push-lr-and-pop-lr-in-arm-arch64 and replaces them with `stp` and `ldp`.

=== Data processing instructions

Arithmetic:

* link:v7/add.S[]
* link:v7/mul.S[]
* link:v7/sub.S[]

Bitwise:

* link:v7/and.S[]
** `eor`: exclusive OR
** `oor`: OR
* link:v7/bic.S[]

Shifts:

* `asr`: Arithmetic Shift Right. Keep sign.
* `lsr`: Logical Shift Right. Insert zeroes sign.
* `ror`: Rotate Right. Wrap bits around.

==== mov

Move an immediate to a register, or a register to another register.

Cannot load from or to memory, since only the `ldr` and `str` instruction families can do that in ARM: <<load-and-store-instructions>>

Example: link:v7/mov.S[]

Since every instruction <<instruction-length,has a fixed 4 byte size>>, there is not enough space to encode arbitrary 32-bit immediates in a single instruction, since some of the bits are needed to actually encode the instruction itself.

The solutions to this problem are mentioned at:

* https://stackoverflow.com/questions/38689886/loading-32-bit-values-to-a-register-in-arm-assembly
* https://community.arm.com/processors/b/blog/posts/how-to-load-constants-in-assembly-for-arm-architecture

Summary of solutions:

* `movw` and `movt`
* place it in memory. But then how to load the address, which is also a 32-bit value?
** use pc-relative addressing if the memory is close enough
** use `orr` encodable shifted immediates

The blog article summarizes nicely which immediates can be encoded and the design rationale:

____
An Operand 2 immediate must obey the following rule to fit in the instruction: an 8-bit value rotated right by an even number of bits between 0 and 30 (inclusive). This allows for constants such as 0xFF (0xFF rotated right by 0), 0xFF00 (0xFF rotated right by 24) or 0xF000000F (0xFF rotated right by 4).

In software - especially in languages like C - constants tend to be small. When they are not small they tend to be bit masks. Operand 2 immediates provide a reasonable compromise between constant coverage and encoding space; most common constants can be encoded directly.
____

Assemblers however support magic memory allocations which may hide what is truly going on: https://stackoverflow.com/questions/14046686/why-use-ldr-over-mov-or-vice-versa-in-arm-assembly Always ask your friendly disassembly for a good confirmation.

==== ubfm

Unsigned Bitfield Move.

____
copies any number of low-order bits from a source register into the same number of
adjacent bits at any position in the destination register, with zeros in the upper and lower bits.
____

Example: link:v8/ubfm.S[]

Operation:

....
dest = (src & ((1 << width) - 1)) >> lsb;
....

Bibliography: https://stackoverflow.com/questions/8366625/arm-bit-field-extract

===== ubfx

Alias for:

....
UBFM <Wd>, <Wn>, #<lsb>, #(<lsb>+<width>-1)
....

== Instruction encoding

Understanding the basics of instruction encodings is fundamental to help you to remember what instructions do and why some things are possible or not.

=== Instruction length

Every ARMv7 instruction is 4 bytes long.

This RISC-y design likely makes processor design easier and allows for certain optimizations, at the cost of slightly more complex assembly. Totally worth it.

<<Thumb>> is an alternative encoding.

=== Thumb

Variable bit encoding where instructions are either 4 or 2 bytes.

In general cannot encode conditional instructions, but <<thumb-2>> can.

Example: link:v7/thumb.S[]

Bibliography:

* https://stackoverflow.com/questions/28669905/what-is-the-difference-between-the-arm-thumb-and-thumb-2-instruction-encodings
* https://reverseengineering.stackexchange.com/questions/6080/how-to-detect-thumb-mode-in-arm-disassembly

=== Thumb-2

Newer version of thumb that allows encoding almost all instructions, TODO example.

Bibliography: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0471i/CHDFEDDB.html

[[aapcs]]
== Calling convention

Call C standard library functions from assembly:

....
make test-c_from_arm
....

Output:

....
hello puts
hello printf 12345678
....

Source: link:v7/c_from_arm.S[]

ARM Architecture Procedure Call Standard (AAPCS) is the name that ARM Holdings gives to the calling convention. 

Official specification: http://infocenter.arm.com/help/topic/com.arm.doc.ihi0042f/IHI0042F_aapcs.pdf

Bibliography:

* https://en.wikipedia.org/wiki/Calling_convention#ARM_(A32) Wiki contains the master list as usual.
* http://stackoverflow.com/questions/8422287/calling-c-functions-from-arm-assembly
* http://stackoverflow.com/questions/261419/arm-to-c-calling-convention-registers-to-save
* https://stackoverflow.com/questions/10494848/arm-whats-the-difference-between-apcs-and-aapcs-abi

== Linux system calls

Do a `write` and `exit` raw Linux system calls:

....
make -C v7/linux test
make -C v8/linux test
....

Outcome for both:

....
hello world
....

Sources:

* link:v7/linux/hello.S[]
* link:v8/linux/hello.S[]

Unlike most our other examples, which use the C standard library for portability, this one can only be run on Linux.

The syscall numbers are defined at:

* v7: https://github.com/torvalds/linux/blob/v4.17/arch/arm/tools/syscall.tbl
* v8: https://github.com/torvalds/linux/blob/v4.17/include/uapi/asm-generic/unistd.h

Bibliography:

* https://stackoverflow.com/questions/12946958/what-is-the-interface-for-arm-system-calls-and-where-is-it-defined-in-the-linux
* https://stackoverflow.com/questions/45742869/linux-syscall-conventions-for-armv8
* https://reverseengineering.stackexchange.com/questions/16917/arm64-syscalls-table

== ARMv8

In this repository we will document only points where ARMv8 differs from ARMv7 behaviour: so you should likely learn ARMv7 first.

ARMv8 is the 64 bit version of the ARM architecture.

It has two states:

* AArch32: 32-bit legacy compatibility mode, similar to ARMv7
* AArch64: 64-bit mode, the main mode of operation

Great summary of differences from AArch32: <https://en.wikipedia.org/wiki/ARM_architecture#AArch64_features>

Some random ones, TODO create clean examples of them:

* the stack has to 16-byte aligned. Therefore, the main way to push things to stack is `ldp` and  `stp`, which push two 8 byte registers at a time

=== ARMv8 movk

Fill a 64 bit register with 4 16-bit instructions one at a time.

Example: link:v8/movk.S[]

Bibliography: https://stackoverflow.com/questions/27938768/moving-a-32-bit-constant-in-arm-arch64-register

=== ARMv8 registers

Example: link:v8/regs.S[]

=== stp

Push a pair of registers to the stack.

TODO minimal example. Currently used on link:v8/commmon_arch.h[] since it is the main way to restore register state.

== Floating point

=== VFP

Vector Floating Point extension.

Example: link:v7/vfp.S[]

Basically not implemented in ARMv8, the wiki says:

____
Some devices such as the ARM Cortex-A8 have a cut-down VFPLite module instead of a full VFP module, and require roughly ten times more clock cycles per float operation.
____

VFP has several revisions, named as VFPv1, VFPv2, etc. TODO: announcement dates.

As mentioned at: https://stackoverflow.com/questions/37790029/what-is-difference-between-arm64-and-armhf/48954012#48954012 the Linux kernel shows those capabilities in `/proc/cpuinfo` with flags such as `vfp vfpv3`.

When a certain version of VFP is present on a CPU, the compiler prefix typically contains the `hf` characters which stands for Hard Float, e.g.: `arm-linux-gnueabihf`. This means that the compiler will emit VFP instructions instead of just using software implementations.

Bibliography:

* [[armarm7]] Appendix D6 "Common VFP Subarchitecture Specification". It is not part of the ISA, but just an extension.
* https://mindplusplus.wordpress.com/2013/06/25/arm-vfp-vector-programming-part-1-introduction/ 
* https://en.wikipedia.org/wiki/ARM_architecture#Floating-point_(VFP)

=== NEON

TODO example

https://developer.arm.com/technologies/neon mentions that is is present on both ARMv7 and ARMv8:

____
NEON technology was introduced to the Armv7-A and Armv7-R profiles. It is also now an extension to the Armv8-A and Armv8-R profiles. 
____

Newer than VFP. TODO announcement date.

Vs <<vfp>>: https://stackoverflow.com/questions/4097034/arm-cortex-a8-whats-the-difference-between-vfp-and-neon

=== SVE

TODO example

Scalable Vector Extension.

aarch64 only, newer than <<neon>>. TODO announcement date. Possibly 2017: https://alastairreid.github.io/papers/sve-ieee-micro-2017.pdf Added to QEMU in 3.0.0.

Official spec: https://developer.arm.com/docs/100891/latest/sve-overview/introducing-sve

== Theory

TODO review all of those and move them into the main README. They are from a previous life.

. link:how-to-play-with-arm.md[How to play with ARM]
. link:versions.md[Versions]
.. link:thumb.md[Thumb]
. link:vs-x86.md[Vs x86]
. link:compilers.md[Compilers]
. link:gas.md[GAS]

=== Introduction to ARM

The link:https://en.wikipedia.org/wiki/ARM_architecture[ARM architecture] is has been used on the vast majority of mobile phones in the 2010's, and on a large fraction of micro controllers.

It competes with x86 because its implementations are designed for low power consumption, which is a major requirement of the cell phone market.

ARM is generally considered a RISC instruction set, although there are some more complex instructions which would not generally be classified as purely RISC.

ARM is developed by the British funded company ARM Holdings: https://en.wikipedia.org/wiki/Arm_Holdings which originated as a joint venture between Acorn Computers, Apple  and VLSI Technology in 1990.

=== Free implementations

The ARM instruction set is itself protected by patents / copyright / whatever, and you have to pay ARM Holdings a licence to implement it with their own custom Verilog code.

This is the case of many major customers, including many Apple's Ax and Qualcomm Snapdragon chips.

ARM has already sued people in the past for implementing ARM ISA: http://www.eetimes.com/author.asp?section_id=36&doc_id=1287452

http://semiengineering.com/an-alternative-to-x86-arm-architectures/ mentions that:

____
Asanovic joked that the shortest unit of time is not the moment between a traffic light turning green in New York City and the cab driver behind the first vehicle blowing the horn; it’s someone announcing that they have created an open-source, ARM-compatible core and receiving a “cease and desist” letter from a law firm representing ARM.
____

This licensing however does have the following fairness to it: ARM Holdings invents a lot of money in making a great open source software environment for the ARM ISA, so it is only natural that it should be able to get some money from hardware manufacturers for using their ISA.

Patents for very old ISAs however have expired, Amber is one implementation of those: https://en.wikipedia.org/wiki/Amber_%28processor_core%29 TODO does it have any application?

Bibliography: https://www.quora.com/Why-is-it-that-you-need-a-license-from-ARM-to-design-an-ARM-CPU-How-are-the-instruction-sets-protected

== Bibliography

ISA quick references can be found in some places however:

- <https://web.archive.org/web/20161009122630/http://infocenter.arm.com/help/topic/com.arm.doc.qrc0001m/QRC0001_UAL.pdf>

Getting started tutorials:

* http://www.davespace.co.uk/arm/introduction-to-arm/
* https://azeria-labs.com/writing-arm-assembly-part-1/

=== Official manuals

The official manuals were stored in http://infocenter.arm.com but as of 2017 they started to slowly move to link:https://developer.arm.com[].

Each revision of a document has a "ARM DDI" unique document identifier.

The "ARM Architecture Reference Manuals" are the official canonical ISA documentation document. In this repository, we always reference the following revisions:

Bibliography: https://www.quora.com/Where-can-I-find-the-official-documentation-of-ARM-instruction-set-architectures-ISAs

[[armarm7]]
==== ARMv7 architecture reference manual

ARMv7: https://developer.arm.com/products/architecture/a-profile/docs/ddi0406/latest/arm-architecture-reference-manual-armv7-a-and-armv7-r-edition

We use: DDI 0406C.d: https://static.docs.arm.com/ddi0406/cd/DDI0406C_d_armv7ar_arm.pdf

[[armarm8]]
==== ARMv8 architecture reference manual

https://developer.arm.com/docs/ddi0487/latest/arm-architecture-reference-manual-armv8-for-armv8-a-architecture-profile

We use: ARM DDI 0487C.a: https://static.docs.arm.com/ddi0487/ca/DDI0487C_a_armv8_arm.pdf

==== Programmer’s Guide for ARMv8-A

https://developer.arm.com/docs/den0024/latest/preface

A more terse human readable introduction to the ARM architecture than the reference manuals.

We use: DEN0024A https://static.docs.arm.com/den0024/a/DEN0024A_v8_architecture_PG.pdf

=== Bare metal

This tutorial only covers userland concepts.

However, certain instructions can only be used in higher privilege levels from an operating system itself.

Here is a bibliography for ARM programming without an operating system, also known as "Bare Metal Programming":

* generic:
** https://stackoverflow.com/questions/38914019/how-to-make-bare-metal-arm-programs-and-run-them-on-qemu/50981397#50981397 generic QEMU question
** link:https://github.com/freedomtan/aarch64-bare-metal-qemu/tree/2ae937a2b106b43bfca49eec49359b3e30eac1b1[]: `-M virt` UART bare metal hello world, nothing else, just works
** https://github.com/bravegnu/gnu-eprog Not tested.
** https://stackoverflow.com/questions/29837892/how-to-run-a-c-program-with-no-os-on-the-raspberry-pi/40063032#40063032 no QEMU restriction
** https://github.com/cirosantilli/raspberry-pi-bare-metal-blinker minimal, but not very QEMU friendly however because hard to observe LED: https://raspberrypi.stackexchange.com/questions/56373/is-it-possible-to-get-the-state-of-the-leds-and-gpios-in-a-qemu-emulation-like-t
* raspberry PI:
** https://raspberrypi.stackexchange.com/questions/34733/how-to-do-qemu-emulation-for-bare-metal-raspberry-pi-images/85135#85135 RPI3 specific
** link:https://github.com/bztsrc/raspi3-tutorial[], getting started: https://raspberrypi.stackexchange.com/questions/34733/how-to-do-qemu-emulation-for-bare-metal-raspberry-pi-images/85135#85135
** https://github.com/dwelch67/raspberrypi
** https://github.com/BrianSidebotham/arm-tutorial-rpi
* gem5:
** https://github.com/tukl-msd/gem5.bare-metal bare metal UART example. Tested with: https://stackoverflow.com/questions/43682311/uart-communication-in-gem5-with-arm-bare-metal/50983650#50983650
* games:
** https://github.com/kcsongor/arm-doom PI 1 model B https://www.youtube.com/watch?v=jeHtktKtGYQ
** https://github.com/Tetris-Duel-Team/Tetris-Duel Demo: https://www.youtube.com/watch?v=hTqKRdcKZ9k
** https://github.com/ICTeam28/PiFox rail shooter https://www.youtube.com/watch?v=-5n9IxSQH1M

x86 bare metal tutorial at: https://github.com/cirosantilli/x86-bare-metal-examples
