= ARM Assembly Cheat
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

ARMv7 and ARMv8 assembly userland minimal examples. Runnable asserts on x86 host with QEMU. Nice GDB step debug setup. Tested on Ubuntu 18.04 host.

toc::[]

== Getting started

Ubuntu 16.04 amd64:

....
./configure
....

Build all examples:

....
make
....

Build and run a single example on an emulator:

....
make test-<basename-no-extension>
....

E.g.:

....
make test-hello_driver
....

will run:

....
hello_driver.S
....

Alternatively, to help with tab complete, the following all do the same thing:

....
./t hello_driver
./t hello_driver.
./t hello_driver.out
....

Almost all example don't output anything, they just assert that the computations are as expected and exit 0 is that was the case.

Try messing with the examples to see them fail. You should see the standard `make` failure message of form:

....
Makefile:61: recipe for target 'test-fail' failed
make: *** [test-fail] Error 1
....

Test that all examples exit with status 0:

....
make test
....

=== GDB step debug

Debug one example with GDB:

....
make gdb-add
....

Bibliography: https://stackoverflow.com/questions/20590155/how-to-single-step-arm-assembler-in-gdb-on-qemu/51310791#51310791

=== Disassemble

Even though <<gdb-step-debug>> can already disassemble instructions for us, it is sometimes useful to have the disassembly in a text file for further examination.

Disassemble all examples:

....
make -j `nproc` objdump
....

Disassemble one example:

....
make add.objdump
....

Examine one disassembly:

....
less -p asm_main add.objdump
....

This jumps directly to `asm_main`, which is what you likely want to see.

Disassembly is still useful even though we are writing assembly because the assembler can do some non-obvious magic that we want to understand.

=== Get rid of distro packages

If you are like me, and you don't trust distro blobs, or if your distro does not provide working blobs, here goes a working procedure to replace the following distro blobs:

* crosstool-ng: https://stackoverflow.com/revisions/51310756/6
* qemu:
+
....
git clone --recursive git://git.qemu.org/qemu.git
cd qemu
git checkout v2.12.0
./configure --target-list=arm-linux-user
make -j`nproc`
....

Then build and run with:

....
make \
  CTNG=crosstool-ng/.build/ct_prefix \
  PREFIX=arm-cortex_a15-linux-gnueabihf \
  QEMU_EXE=arm-linux-user/qemu-arm \
  test \
;
....

Ideally we should just add submodules here and automate from there, but I've done that like 5 times this month and I'm lazy now.

== About

Top level examples target the armv7 ISA (32-bit). New AArch64 features will be put in subdirectory.

`qemu-arm-static` is used for emulation. It translates ARM to x86, and forwards system calls to the kernel.

OS portability is achieved with the C standard library which makes system calls for us.

Non OS portable examples will be clearly labeled with their OS.

== Infrastructure

These examples show how our tooling works:

. link:fail.S[]
. link:hello_c.c[]
. link:hello_driver.S[]

== Instructions

Grouping loosely based on that of the manual.

=== Branch instructions

. link:beq.S[]
. link:b.S[]
. link:bl.S[]

=== Load and store instructions

In ARM, there are only two instruction families that do memory access: `ldr` and `str`:

Examples:

* link:ldr.S[]
* link:str.S[]

Everything else works on register and immediates.

This is part of the RISC-y beauty of the ARM instruction set, unlike x86 in which several operations can read from memory, and helps to predict how to optimize for a given CPU pipeline.

=== Data processing instructions

. link:add.S[]
. link:and.S[]
. link:mul.S[]
. link:sub.S[]

==== mov

Move an immediate to a register.

Example: link:mov.S[]

Since every instruction <<instruction-length,has a fixed 4 byte size>>, there is not enough space to encode arbitrary 32-bit immediates in a single instruction, since some of the bits are needed to actually encode the instruction itself.

The solutions to this problem are mentioned at:

* https://stackoverflow.com/questions/38689886/loading-32-bit-values-to-a-register-in-arm-assembly
* https://community.arm.com/processors/b/blog/posts/how-to-load-constants-in-assembly-for-arm-architecture

Summary of solutions:

* `movw` and `movt`
* place it in memory. But then how to load the address, which is also a 32-bit value?
** use pc-relative addressing if the memory is close enough
** use `orr` encodable shifted immediates

The blog article summarizes nicely which immediates can be encoded and the design rationale:

____
An Operand 2 immediate must obey the following rule to fit in the instruction: an 8-bit value rotated right by an even number of bits between 0 and 30 (inclusive). This allows for constants such as 0xFF (0xFF rotated right by 0), 0xFF00 (0xFF rotated right by 24) or 0xF000000F (0xFF rotated right by 4).

In software - especially in languages like C - constants tend to be small. When they are not small they tend to be bit masks. Operand 2 immediates provide a reasonable compromise between constant coverage and encoding space; most common constants can be encoded directly.
____

Assemblers however support magic memory allocations which may hide what is truly going on: https://stackoverflow.com/questions/14046686/why-use-ldr-over-mov-or-vice-versa-in-arm-assembly Always ask your friendly disassembly for a good confirmation.

==== push

. link:push.S[]

== Instruction encoding

=== Instruction length

Every ARMv7 instruction is 4 bytes long.

This RISC-y design likely makes processor design easier and allows for certain optimizations, at the cost of slightly more complex assembly. Totally worth it.

<<Thumb>> is an alternative encoding.

=== Thumb

Variable bit encoding where instructions are either 4 or 2 bytes.

In general cannot encode conditional instructions, but <<thumb-2>> can.

Example:

....
make run-thumb
....

Outcome: it does not blow up.

Source:

* link:driver_thumb.c[]
* link:thumb.S[]

https://stackoverflow.com/questions/28669905/what-is-the-difference-between-the-arm-thumb-and-thumb-2-instruction-encodings

=== Thumb-2

Newer version of thumb that allows encoding almost all instructions, TODO example.

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0471i/CHDFEDDB.html

== Calling convention

http://stackoverflow.com/questions/8422287/calling-c-functions-from-arm-assembly

Call the C `puts("hello world")` and `exit(0)` functions from assembly:

....
make run-c_from_arm
....

Source: link:c_from_arm.S[]

Don't forget that stack must be 8 byte aligned.

== Linux system calls

Do a `write` and `exit` raw Linux system calls:

....
make -C linux
....

Outcome:

....
hello world
....

Source: link:linux/hello.S[].

Unlike most our other examples, which use the C standard library for portability, this one can only be run on Linux.

== Theory

. link:how-to-play-with-arm.md[How to play with ARM]
. link:introduction.md[Introduction]
. link:versions.md[Versions]
.. link:aarch64.md[AArch64]
. link:calling-conventions.md[Calling conventions]
. link:extensions.md[Extensions]
.. link:thumb.md[Thumb]
. link:vs-x86.md[Vs x86]
. link:compilers.md[Compilers]
. link:free-implementations.md[Free implementations]
. link:gas.md[GAS]
. link:registers.md[Registers]
. link:flags.md[Flags]
. link:system-programming.md[System programming]
. link:isa-documentation.md[ISA documentation]
. link:glossary.md[Glossary]

== Bibliography

ISA quick references can be found in some places however:

- <https://web.archive.org/web/20161009122630/http://infocenter.arm.com/help/topic/com.arm.doc.qrc0001m/QRC0001_UAL.pdf>

Getting started tutorials:

* http://www.davespace.co.uk/arm/introduction-to-arm/
* https://azeria-labs.com/writing-arm-assembly-part-1/

=== Official manuals

The official manuals were stored in http://infocenter.arm.com but as of 2017 they started to slowly move to link:https://developer.arm.com[].

Each revision of a document has a "ARM DDI" unique document identifier.

The "ARM Architecture Reference Manuals" are the official canonical ISA documentation document. In this repository, we always reference the following revisions:

* ARMv8: https://developer.arm.com/docs/ddi0487/latest/arm-architecture-reference-manual-armv8-for-armv8-a-architecture-profile
+
We use: ARM DDI 0487C.a: https://static.docs.arm.com/ddi0487/ca/DDI0487C_a_armv8_arm.pdf
* ARMv7: https://developer.arm.com/products/architecture/a-profile/docs/ddi0406/latest/arm-architecture-reference-manual-armv7-a-and-armv7-r-edition
+
We use: DDI 0406C.d: https://static.docs.arm.com/ddi0406/cd/DDI0406C_d_armv7ar_arm.pdf?_ga=2.64816815.1086219598.1531250756-677810532.1526807026

Bibliography: https://www.quora.com/Where-can-I-find-the-official-documentation-of-ARM-instruction-set-architectures-ISAs
